import { spawnSync } from "node:child_process";
import { appendFileSync, writeFileSync } from "node:fs";
import path from "node:path";

interface CommandResult {
  stderr: string;
  stdout: string;
}

interface RuntimeResult {
  caseName: string;
  mean: string;
}

const runCommand = (args: string[]): CommandResult => {
  const result = spawnSync("bun", args, {
    encoding: "utf-8",
    stdio: ["ignore", "pipe", "pipe"],
  });

  const stdout = result.stdout ?? "";
  const stderr = result.stderr ?? "";

  if (stderr) {
    process.stderr.write(stderr);
  }

  if (stdout) {
    process.stdout.write(stdout);
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }

  return { stderr, stdout };
};

const rootDir = path.join(import.meta.dirname, "..");
const reportPath = path.join(rootDir, "BENCHMARK_REPORT.md");
const escapeCharacter = String.fromCodePoint(27);
const ansiPattern = new RegExp(`${escapeCharacter}\\[[0-9;]*m`, "gu");

const section = (title: string, body: string): string =>
  `## ${title}\n\n${body.trim()}\n`;

const codeBlock = (contents: string): string =>
  `\`\`\`text\n${contents.trim()}\n\`\`\``;

const stripAnsi = (value: string): string => value.replace(ansiPattern, "");

const parseRuntimeResults = (output: string): RuntimeResult[] =>
  [...output.matchAll(/^(.+?)\s+([0-9.]+)\s+(ns|µs|ms)\/iter\b/gmu)].map(
    ([, caseName, value, unit]) => ({
      caseName: caseName.trim(),
      mean: `${value} ${unit}/iter`,
    })
  );

const runtimeSummaryTable = (output: string): string => {
  const rows = parseRuntimeResults(output);

  if (rows.length === 0) {
    return "Runtime summary could not be parsed from benchmark output.";
  }

  return [
    "| Case | Avg |",
    "| --- | ---: |",
    ...rows.map(({ caseName, mean }) => `| ${caseName} | ${mean} |`),
  ].join("\n");
};

const writeReport = ({
  runtime,
  size,
  startup,
}: {
  runtime: string;
  size: string;
  startup: string;
}): void => {
  const generatedAt = new Date().toISOString();
  const report = [
    "# Benchmark Report",
    "",
    `Generated by \`bun run perf\` at \`${generatedAt}\`.`,
    "",
    "This report is local and machine-dependent. Compare CI output against recent runs from the same environment before treating changes as regressions.",
    "",
    section(
      "What This Covers",
      [
        "- published ESM and CJS runtime benchmarks from `dist`",
        "- cold startup/import timings",
        "- `dist` file sizes, consumer bundle size, and npm package size",
      ].join("\n")
    ),
    section("Runtime Summary", runtimeSummaryTable(runtime)),
    section("Runtime Details", codeBlock(runtime)),
    section("Startup Benchmarks", startup),
    section("Size Report", size),
    section(
      "Interpretation Notes",
      [
        "- Default unbounded generation should remain in the nanosecond range.",
        "- High `segments` cases show scaling cost from uniqueness checks.",
        "- Bounded `maxLength` cases are currently the slowest runtime path.",
        "- Startup/import timing includes eager loading of all word-list data.",
        "- Consumer bundle gzip size tracks the browser cost of a normal import.",
      ].join("\n")
    ),
    "",
  ].join("\n");

  writeFileSync(reportPath, report);
};

runCommand(["run", "build"]);

const runtimeBenchmark = runCommand(["benchmarks/joyful.bench.ts"]);
const runtimeOutput = stripAnsi(runtimeBenchmark.stdout);

const githubStepSummary = process.env.GITHUB_STEP_SUMMARY;

if (githubStepSummary) {
  appendFileSync(
    githubStepSummary,
    `## Runtime Benchmarks\n\n\`\`\`\n${runtimeOutput}\`\`\`\n\n`
  );
}

const startupBenchmark = runCommand(["benchmarks/startup.bench.ts"]);
const sizeReport = runCommand(["scripts/size.ts"]);

writeReport({
  runtime: runtimeOutput,
  size: stripAnsi(sizeReport.stdout),
  startup: stripAnsi(startupBenchmark.stdout),
});

console.log(
  `Benchmark report written to ${path.relative(rootDir, reportPath)}`
);
